config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :places
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
  class Place < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_place, only: [:show, :edit, :update]

  def index
    if params[:query].present?
      sql_query = "name ILIKE :query OR address ILIKE :query"
      @places = Place.where(sql_query, query: "%#{params[:query]}%")
    else
      @places = Place.where.not(latitude: nil)
    end
    @markers = @places.map do |place|
    {
      lat: place.latitude,
      lng: place.longitude
    }
    end
  end

  def show
    @place_coordinates = { lat: @place.latitude, lng: @place.longitude }
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.create(params_place)
    redirect_to places_path
  end

  def edit
  end

  def update
    @place.update(params_place)
    if @place.save
      redirect_to places_path
    else
      render :edit
    end
  end

  private

  def params_place
    params.require(:place).permit(:name, :urlphoto, :distance, :address, :latitude, :longitude, :content)
  end

  def set_place
    @place = Place.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>BAPI</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/navbar' %>
<div class="home-main-container">
  <%= link_to 'Enter', places_path, class:'home-link' %>
</div>

app/views/places/edit.html.erb
<%= render 'shared/navbar' %>
<div class="form-main-container">
  <h2>Edit <%= @place.name  %></h2>
  <div class="row">
    <div class="col-xs-offset-2 col-xs-8">
      <%= simple_form_for @place do |f| %>
        <%= f.input  :name %>
        <div id="place_address">
          <%= f.input  :address %>
        </div>
        <%= f.input  :content %>
        <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>

<%= content_for(:after_js) do %>
  <script>
    $(document).ready(function() {
      alert('Bienvenue <%= @place.name %>');
    });
  </script>
<% end %>

app/views/places/index.html.erb
<div class="index-main-container">
  <div class="index-places-container">
    <div class="row">
      <div class="col-xs-12">
        <%= render 'shared/navbar' %>
        <h2>All places</h2>
        <%= form_tag places_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a place"
          %>
        <% end %>
        <% @places.each do |place| %>
          <div class="index-main-card">
            <div class="index-card-left">
              <h4><%= place.name %></h4>
              <p><%= place.address %></p>
              <p><%= truncate(place.content, length: 200) %></p>
            </div>
            <div class="index-card-right">
              <%= link_to edit_place_path(place) do %>
                <i class="far fa-edit"></i>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div id="map" data-markers="<%= @markers.to_json %>"></div>
</div>

<%= content_for(:after_js) do %>
  <%= javascript_pack_tag 'map' %>
<% end %>

app/views/places/new.html.erb
<%= render 'shared/navbar' %>
<div class="form-main-container">
  <h2>Create your own place</h2>
  <div class="row">
    <div class="col-xs-offset-2 col-xs-8">
      <%= simple_form_for @place do |f| %>
        <%= f.input  :name, placeholder: 'What is its name' %>
        <%= f.input  :address, id:"place_address", placeholder: 'Enter the address' %>
        <%= f.input  :content, placeholder: 'Add a description' %>
        <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/places/show.html.erb
<%= @place.name %>

<% content_for(:after_js) do %>
  <script>
    $(document).ready(function() {
      console.log(<%= raw @place_coordinates.to_json %>);
      // alert('Bienvenue <%= @place.name %>');
    });
  </script>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand", style:'font-size:1.5em' do %>
    <i class="fas fa-home"></i>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Places", places_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Create", new_place_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <div class= "avatar dropdown-toggle", id= "navbar-wagon-menu", data-toggle="dropdown", style="font-size: 1.5em">
            <i class="far fa-smile"></i>
           </div>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <% if user_signed_in? %>
          <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to 'Places', places_path %></li>
            <li><%= link_to 'Create', new_place_path %></li>
          </ul>
        <% else %>
          <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <% end %>
      </div>
  </div>
</div>